
var messages =[
            "Thanks a bunch!",
            "Much obliged!",
            "We're deeply grateful.",
            "We can't thank you enough.",
            "You've been a lifesaver!",
            "We owe you one.",
            "It means the world to us.",
            "We appreciate your kindness.",
            "You're a true friend.",
            "Our sincerest thanks.",
            "You're a gem!",
            "You're a star!",
            "We're in your debt.",
            "You're the best!",
            "We can never repay you.",
            "We're touched by your generosity.",
            "You've made Our day!",
            "You're a lifesaver!",
            "You make a difference.",
            "We're thankful for your support.",
            "We're indebted to you.",
            "You're a true blessing.",
            "You're a hero!",
            "You're a rockstar!",
            "You've been so kind.",
            "We're forever grateful.",
            "You're a godsend!",
            "We're over the moon!",
            "You've been wonderful.",
            "You're incredible!",
            "We can't express Our gratitude enough.",
            "You've been a great help.",
            "We're thankful for your assistance.",
            "You're a lifesaver!",
            "You're a true friend.",
            "We appreciate your support.",
            "You're a wonderful person.",
            "You've been amazing.",
            "We can't thank you sufficiently.",
            "You're a true hero!",
            "You're a true blessing.",
            "You're a lifesaver!",
            "We're eternally grateful.",
            "You're a lifesaver!",
            "You're a true gem.",
            "You've been a great friend.",
            "We're thankful for your presence.",
            "You're a ray of sunshine.",
            "You're a treasure.",
            "You're one in a million.",
            "You're a superstar!",
            "We're grateful beyond words.",
            "You're Our savior!",
            "We're deeply appreciative.",
            "You've made a big difference.",
            "You're a true saint.",
            "We're filled with gratitude.",
            "You're an angel in disguise.",
            "You're a true star.",
            "You're a blessing in Our life.",
            "You're a miracle worker!",
            "You're Our hero!",
            "You're a gift from heaven.",
            "We're forever in your debt.",
            "You're a lifesaver!",
            "You're a true friend indeed.",
            "You're a true inspiration.",
            "We're deeply moved.",
            "You're a beacon of light.",
            "You're a true legend.",
            "We're overwhelmed with gratitude.",
            "You're a true warrior.",
            "You're a true champion.",
            "We're thankful for your wisdom.",
            "You're a true role model.",
            "You're a true mentor.",
            "You're a true leader.",
            "You're a true visionary.",
            "You're a true artist.",
            "You're a true genius.",
            "You're a true innovator.",
            "You're a true pioneer.",
            "You're a true trailblazer.",
            "You're a true legend.",
            "You're a true hero.",
            "You're a true genius.",
            "You're a true artist.",
            "You're a true leader.",
            "You're a true visionary.",
            "You're a true mentor.",
            "You're a true role model.",
            "You're a true champion.",
            "You're a true warrior.",
            "You're a beacon of light.",
            "You're a true inspiration.",
            "We're deeply moved.",
            "You're a true friend indeed.",
            "You're a lifesaver!",
            "We're forever in your debt.",
            " You're Our hero!",
            " You're a gift from heaven.",
            " You're a true star.",
            " You're an angel in disguise.",
            " We're filled with gratitude.",
            " You're a true saint.",
            " You've made a big difference.",
            " You're deeply appreciated.",
            " We're thankful for your help.",
            " You're a true gem.",
            " You're a treasure.",
            " You're one in a million.",
            " You're a superstar!",
            " We're grateful beyond words.",
            " You're Our savior!",
            " We're deeply grateful.",
            " You're a ray of sunshine.",
            " You're a blessing in Our life.",
            " You're a miracle worker!",
            " You've been amazing.",
            " We can't thank you sufficiently.",
            " You're a true hero!",
            " You're a true blessing.",
            " You're a lifesaver!",
            " We're eternally grateful.",
            " You're a lifesaver!",
            " You're a true friend.",
            " Weappreciate your support.",
            " You're a wonderful person.",
            " You've been wonderful.",
            " We can't express Our gratitude enough.",
            " You're a true hero!",
            " You're a true blessing.",
            " You're a lifesaver!",
            " We're overwhelmed with gratitude.",
            " You're a true warrior.",
            " You're a true champion.",
            " We're thankful for your wisdom.",
            " You're a true role model.",
            " You're a true mentor.",
            " You're a true leader.",
            " You're a true visionary.",
            " You're a true artist.",
            " You're a true genius.",
            " You're a true innovator.",
            " You're a true pioneer.",
            " You're a true trailblazer.",
            " You're a true legend.",
            " You're a true hero.",
            " You're a true genius.",
            " You're a true artist.",
            " You're a true leader.",
            " You're a true visionary.",
            " You're a true mentor.",
            " You're a true role model.",
            " You're a true champion.",
            " You're a true warrior.",
            " You're a beacon of light.",
            " You're a true inspiration.",
            " We're deeply moved.",
            " You're a true friend indeed.",
            " You're a lifesaver!",
            " We're forever in your debt.",
            " You're Our hero!",
            " You're a gift from heaven.",
            " You're a true star.",
            " You're an angel in disguise.",
            " We're filled with gratitude.",
            " You're a true saint.",
            " You've made a big difference.",
            " You're deeply appreciated.",
            " We're thankful for your help.",
            " You're a true gem.",
            " You're a treasure.",
            " You're one in a million.",
            " You're a superstar!",
            " We're grateful beyond words.",
            " You're Our savior!",
            " We're deeply grateful.",
            " You're a ray of sunshine.",
            " You're a blessing in Our life.",
            " You're a miracle worker!",
            " You've been amazing.",
            " We can't thank you sufficiently.",
            " You're a true hero!",
            " You're a true blessing.",
            " You're a lifesaver!",
            " We're eternally grateful.",
            " You're a lifesaver!",
            " You're a true friend.",
            " We appreciate your support.",
            " You're a wonderful person.",
            " You've been wonderful.",
            " We can't express Our gratitude enough.",
            " You're a true hero!",
            " You're a true blessing.",
            " You're a lifesaver!",
            " We're overwhelmed with gratitude.",
            " You're a true warrior.",
            " You're a true champion.",
            " We're thankful for your wisdom.",
            " You're a true role model.",
            " You're a true mentor.",
            " You're a true leader.",
            " You're a true visionary.",
            " You're a true artist.",
            " You're a true genius.",
            " You're a true innovator.",
            " You're a true pioneer.",
            " You're a true trailblazer.",
            " You're a true legend.",
            " You're a true hero.",
            " You're a true genius.",
            " You're a true artist.",
            " You're a true leader.",
            " You're a true visionary.",
            " You're a true mentor.",
            " You're a true role model.",
            " You're a true champion.",
            " You're a true warrior.",
            " You're a beacon of light.",
            " You're a true inspiration.",
            " We're deeply moved.",
            " You're a true friend indeed.",
            " You're a lifesaver!",
            " We're forever in your debt.",
            " You're Our hero!",
            " You're a gift from heaven.",
            " You're a true star.",
            " You're an angel in disguise.",
            " We're filled with gratitude.",
            " You're a true saint.",
            " You've made a big difference.",
            " You're deeply appreciated.",
            " We're thankful for your help.",
            " You're a true gem.",
            " You're a treasure.",
            " You're one in a million.",
            " You're a superstar!",
            " We're grateful beyond words.",
            " You're Our savior!",
            " We're deeply grateful.",
            " You're a ray of sunshine.",
            " You're a blessing in Our life.",
            " You're a miracle worker!",
            " You've been amazing.",
            " We can't thank you sufficiently.",
            " You're a true hero!",
            " You're a true blessing.",
            " You're a lifesaver!",
            " We're eternally grateful.",
            " You're a lifesaver!",
            " You're a true friend.",
            " We appreciate your support.",
            " You're a wonderful person.",
            " You've been wonderful.",
            " We can't express Our gratitude enough.",
            " You're a true hero!",
            " You're a true blessing.",
            " You're a lifesaver!",
            " We're overwhelmed with gratitude.",
            " You're a true warrior.",
            " You're a true champion.",
            " We're thankful for your wisdom.",
            " You're a true role model.",
            " You're a true mentor.",
            " You're a true leader.",
            " You're a true visionary.",
            " You're a true artist.",
            " You're a true genius.",
            " You're a true innovator.",
            " You're a true pioneer.",
            " You're a true trailblazer.",
            " You're a true legend.",
            " You're a true hero.",
            " You're a true genius.",
            " You're a true artist.",
            " You're a true leader.",
            " You're a true visionary.",
            " You're a true mentor.",
            " You're a true role model.",
            " You're a true champion.",
            " You're a true warrior.",
            " You're a beacon of light.",
            " You're a true inspiration.",
            " We're deeply moved.",
            " You're a true friend indeed.",
            " You're a lifesaver!",
            " We're forever in your debt.",
            " You're Our hero!",
            " You're a gift from heaven.",
            " You're a true star.",
            " You're an angel in disguise.",
            " We're filled with gratitude.",
            " You're a true saint.",
            " You've made a big difference.",
            " You're deeply appreciated.",
            " We're thankful for your help.",
            " You're a true gem.",
            " You're a treasure.",
            " You're one in a million"];

document.addEventListener("DOMContentLoaded", function () {
    const messageElement = document.getElementById("message");
    const showMessageButton = document.getElementById("showMessage");

    showMessageButton.addEventListener("click", function () {
console.log('made it here');
                const randomIndex = Math.floor(Math.random() * messages.length);
                const randomMessage = messages[randomIndex];
                messageElement.textContent = randomMessage;
            })
});
